#!/bin/sh

[ -z "$1" ] && {
	echo "need config file directory"
	return
}

CONFDIR=$1"/"
REALIP="/jffs/winq_server/realip"

[ ! -d "$CONFDIR" ] && {
	echo "$CONFDIR is not a directory"
	return
}

[ -n "$2" ] && {
	DOMAIN=`getrealipwinq.sh`

	if [ -z "$DOMAIN" ];then
		DOMAIN=$(cat $REALIP)
	else
		echo $DOMAIN > $REALIP
	fi

	[ -n "$DOMAIN" ] && {
		FILES=$(ls ${CONFDIR} | grep "\.bak")                                                         
		for FILE in $FILES;do                                                                          
		    sed -i "s/remote \([0-9.]\{1,\}\) \([0-9]\{1,\}\)/remote $DOMAIN \2/" ${CONFDIR}${FILE}
		    echo "dhcp-option DNS 9.9.9.9" >> ${CONFDIR}${FILE}
		    echo "dhcp-option DNS 8.8.8.8" >> ${CONFDIR}${FILE}
		    echo "dhcp-option DNS 1.1.1.1" >> ${CONFDIR}${FILE}
		    echo "dhcp-option DNS 114.114.114.114" >> ${CONFDIR}${FILE}
		    #echo "dhcp-option DNS 119.29.29.29" >> ${CONFDIR}${FILE}
		done
	}

	return
}

DOMAIN=`cat /jffs/winq_server/realip`
NEWDOMAIN=`getrealipwinq.sh`
	
[ -z "$NEWDOMAIN" ] && {
	NEWDOMAIN=$DOMAIN
}

[ -n "$NEWDOMAIN" ] && {
	[ -z "$DOMAIN" -o "$NEWDOMAIN" != "$DOMAIN" ] && {
		DOMAIN="$NEWDOMAIN"
		echo $DOMAIN > /jffs/winq_server/realip
		
		FILES=$(ls ${CONFDIR} | grep "\.ovpn")
		for FILE in $FILES;do
			sed -i "s/remote \([0-9.]\{1,\}\) \([0-9]\{1,\}\)/remote $DOMAIN \2/" ${CONFDIR}${FILE}
		done
	}
}
